# Site settings
title: BitBuilders
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://massate.github.io" # the subpath of your site, e.g. /blog/
url: "/sitodiprova" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
